# Generated by Django 5.1.5 on 2025-02-26 06:42

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='+996', max_length=14)),
                ('experience', models.PositiveIntegerField(default=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('salary', models.CharField(default='Заработная плата Младшего разработчика составляет 600$', max_length=255)),
                ('education', models.CharField(max_length=250)),
                ('last_job', models.CharField(blank=True, max_length=250, null=True)),
                ('projects', models.TextField(blank=True, max_length=250, null=True)),
                ('programming_languages', models.TextField(max_length=250)),
                ('awards', models.TextField(blank=True, max_length=250, null=True)),
                ('address', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
