# Generated by Django 5.1.5 on 2025-02-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='image',
        ),
    ]
