# Generated by Django 5.1.5 on 2025-02-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Clothes',
        ),
        migrations.AlterModelTable(
            name='clothes',
            table='clothes',
        ),
    ]
