# Generated by Django 5.1.5 on 2025-02-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_appl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezkaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
